export const KeysiItems = [
    { className: 'Keysi__item-Ctitle',
      classImg: 'Keysi__item-img',
      text: 'Эти слова совершенно справедливы, однако гипнотический рифф продолжает паузный пласт.',
      title: 'Настройка выгрузки YML для Яндекс.Маркета',
      classDat:'Keysi__item-dat',
      dat: '22.04.2019',
      img: 'images/image11.jpg',
      alt: 'one'
    },
    { className: 'Keysi__item-title',
      classImg: 'Keysi__item-img',
      title: 'Настройка выгрузки YML для Яндекс.Маркета',
      classDat:'Keysi__item-dat',
      img: 'images/image22.jpg',
      alt: 'two'
    },
    { className: 'Keysi__item-Btitle',
      classImg: 'Keysi__item-Nimg',
      title: 'Настройка выгрузки YML для Яндекс.Маркета',
      classDat:'Keysi__item-Cdat',
      dat: '22.04.2019',
      img: 'images/image33.jpg',
      alt: 'three'
    },
    { className: 'Keysi__item-Btitle',
      classImg: 'Keysi__item-Nimg',
      title: 'Настройка выгрузки YML для Яндекс.Маркета',
      classDat:'Keysi__item-Cdat',
      dat: '22.04.2019',
      img: 'images/image44.jpg',
      alt: 'four'
    },
    { className: 'Keysi__item-Ctitle',
      classImg: 'Keysi__item-img',
      text: 'Эти слова совершенно справедливы, однако гипнотический рифф продолжает паузный пласт.',
      classDat:'Keysi__item-dat',
      dat: '22.04.2019',
      title: 'Настройка выгрузки YML для Яндекс.Маркета',
      img: 'images/image55.jpg',
      alt: 'five'
    },
    { className: 'Keysi__item-title',
      classImg: 'Keysi__item-img',
      title: 'Настройка выгрузки YML для Яндекс.Маркета',
      classDat:'Keysi__item-dat',
      img: 'images/image66.jpg',
      alt: 'six'
    },
    { className: 'Keysi__item-Btitle',
      classImg: 'Keysi__item-Nimg',
      title: 'Настройка выгрузки YML для Яндекс.Маркета',
      classDat:'Keysi__item-Cdat',
      dat: '22.04.2019',
      img: 'images/image77.jpg',
      alt: 'seven'
    },
  ];